# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Anonymous
email: anonymousband@yahoo.co.uk
description: > # this means to ignore newlines until "baseurl:"
  Anonymous is a band that plays our own music and plays well known music as well.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: 
github_username:  anonymousband
paginate: 1
paginate_path: "/blog/page:num/"

# Build settings
markdown: kramdown
